/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MediaType = IDL.Variant({
  'video' : IDL.Null,
  'photo' : IDL.Null,
});
export const AdminMetrics = IDL.Record({
  'totalMedia' : IDL.Nat,
  'visitCount' : IDL.Nat,
  'totalCapsules' : IDL.Nat,
  'totalNotes' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalNeuronEntries' : IDL.Nat,
});
export const Time = IDL.Int;
export const Beneficiary = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'hashedPassword' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const Media = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'blobId' : IDL.Text,
  'mediaType' : MediaType,
});
export const Note = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
});
export const NeuronEntry = IDL.Record({
  'dissolveDate' : IDL.Text,
  'notes' : IDL.Text,
  'neuronId' : IDL.Text,
  'designatedController' : IDL.Text,
  'votingPreferences' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBeneficiary' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'beneficiaryLogin' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'beneficiaryLogout' : IDL.Func([IDL.Text], [], []),
  'createCapsule' : IDL.Func([], [], []),
  'createMedia' : IDL.Func([IDL.Text, IDL.Text, MediaType], [IDL.Text], []),
  'createNeuronEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createNote' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteCapsule' : IDL.Func([], [], []),
  'deleteMedia' : IDL.Func([IDL.Text], [], []),
  'deleteNeuronEntry' : IDL.Func([IDL.Text], [], []),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'getAdminMetrics' : IDL.Func([], [AdminMetrics], ['query']),
  'getBeneficiaries' : IDL.Func([], [IDL.Vec(Beneficiary)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterId' : IDL.Func([], [IDL.Principal], ['query']),
  'getCapsuleLockStatus' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'getCapsuleMedia' : IDL.Func([IDL.Principal], [IDL.Vec(Media)], ['query']),
  'getCapsuleNotes' : IDL.Func([IDL.Principal], [IDL.Vec(Note)], ['query']),
  'getCycleBalance' : IDL.Func([], [IDL.Nat], []),
  'getGlobalInstructions' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getNeuronEntries' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(NeuronEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdminSetup' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isLoggedInToBeneficiarySession' : IDL.Func(
      [IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'recordVisit' : IDL.Func([], [], []),
  'removeBeneficiary' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setGlobalInstructions' : IDL.Func([IDL.Text], [], []),
  'setupFirstAdmin' : IDL.Func([], [], []),
  'toggleCapsuleLock' : IDL.Func([], [], []),
  'updateNeuronEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'validateBeneficiarySession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MediaType = IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null });
  const AdminMetrics = IDL.Record({
    'totalMedia' : IDL.Nat,
    'visitCount' : IDL.Nat,
    'totalCapsules' : IDL.Nat,
    'totalNotes' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalNeuronEntries' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Beneficiary = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'hashedPassword' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const Media = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'blobId' : IDL.Text,
    'mediaType' : MediaType,
  });
  const Note = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
  });
  const NeuronEntry = IDL.Record({
    'dissolveDate' : IDL.Text,
    'notes' : IDL.Text,
    'neuronId' : IDL.Text,
    'designatedController' : IDL.Text,
    'votingPreferences' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBeneficiary' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'beneficiaryLogin' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'beneficiaryLogout' : IDL.Func([IDL.Text], [], []),
    'createCapsule' : IDL.Func([], [], []),
    'createMedia' : IDL.Func([IDL.Text, IDL.Text, MediaType], [IDL.Text], []),
    'createNeuronEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createNote' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteCapsule' : IDL.Func([], [], []),
    'deleteMedia' : IDL.Func([IDL.Text], [], []),
    'deleteNeuronEntry' : IDL.Func([IDL.Text], [], []),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'getAdminMetrics' : IDL.Func([], [AdminMetrics], ['query']),
    'getBeneficiaries' : IDL.Func([], [IDL.Vec(Beneficiary)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterId' : IDL.Func([], [IDL.Principal], ['query']),
    'getCapsuleLockStatus' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'getCapsuleMedia' : IDL.Func([IDL.Principal], [IDL.Vec(Media)], ['query']),
    'getCapsuleNotes' : IDL.Func([IDL.Principal], [IDL.Vec(Note)], ['query']),
    'getCycleBalance' : IDL.Func([], [IDL.Nat], []),
    'getGlobalInstructions' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getNeuronEntries' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(NeuronEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdminSetup' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isLoggedInToBeneficiarySession' : IDL.Func(
        [IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'recordVisit' : IDL.Func([], [], []),
    'removeBeneficiary' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setGlobalInstructions' : IDL.Func([IDL.Text], [], []),
    'setupFirstAdmin' : IDL.Func([], [], []),
    'toggleCapsuleLock' : IDL.Func([], [], []),
    'updateNeuronEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'validateBeneficiarySession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };